### ISSUE TITLE
modify(trim) not working

### ISSUE THREAD

**Issue by cosmo9able** [biblius/validify#15]
Estou usando:

#[derive(InputObject, Validify)]
pub struct CriarEnderecoDTO {
    #[modify(lowercase, trim)]
    #[graphql(validator(min_length = 1))]
    pub logradouro: String,
    pub numero: Option<u16>,
    #[modify(lowercase, trim)]
    #[graphql(validator(min_length = 1))]
    pub complemento: Option<String>,
    #[modify(lowercase, trim)]
    #[graphql(validator(min_length = 1))]
    pub bairro: String,
    #[graphql(validator(regex = "^[0-9]{8}$"))]
    pub cep: String,
    pub cidade_id: u32,
}

Dados passados na struct: 
{
    logradouro: "rua dos Testes     ",
    numero: 484,
    complemento: " apto rua Teste novo",
    bairro: "Tes Dos Tesssteees     ",
    cep: "01234000",
    cidade_id: 1234308 
  }

Dados ao ler a struct:
{
      "id": "64b80046b3971a8d46256fff",
      "logradouro": "rua dos testes     ",
      "numero": 484,
      "complemento": " apto rua Teste novo",
      "bairro": "tes dos tesssteees     ",
      "cep": "01234000",
      "cidade_id": 1234308
}
    
O lowercase funciona perfeitamente, porém o trim não, teste com 1 ou mais espaços, e mesmo assim não funciona.

**Comment by biblius** [comment]
Strange, I can't reproduce the behaviour. [Wrote a test](https://github.com/biblius/validify/blob/master/derive_tests/tests/modify.rs) for the specific use case and it passes with no problems.
